In [ ]:
import polars as pl 
import pandas as pd
import os
import numpy as np
from pathlib import Path
import re
import sys
sys.path.append(os.path.abspath("../src/utils"))
from preprocess import * 
from plotting import *
from training import *


lifelong_dir = Path("../data/lifelong/processed/to_train")
embryo_dir = Path("../data/embryo/processed/to_train")

lifelong_files = sorted(lifelong_dir.glob("*.parquet"))
embryo_files = sorted(embryo_dir.glob("*.parquet"))

print(lifelong_files)
print(embryo_files)

[PosixPath('../../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_cpm_l0_q0__seqs.parquet'), PosixPath('../../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_cpm_l1_q0__seqs.parquet'), PosixPath('../../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_cpm_l1_q1__seqs.parquet'), PosixPath('../../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_raw_l0_q0__seqs.parquet'), PosixPath('../../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_raw_l1_q0__seqs.parquet'), PosixPath('../../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_raw_l1_q1__seqs.parquet')]
[PosixPath('../../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l0_q0__seqs.parquet'), PosixPath('../../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l1_q0__seqs.parquet'), PosixPath('../../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l1_q1__seqs.parquet'), PosixPath('../../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_raw_l0_q0__seqs.parquet'), PosixPath('../../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_raw_l1_q0__seqs.parquet'), PosixPath('../../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_raw_l1_q1__seqs.parquet')]

In [5]:
lifelong_dfs = [pl.read_parquet(f) for f in lifelong_files]
embryo_dfs   = [pl.read_parquet(f) for f in embryo_files]

In [ ]:
lifelong_dir = Path("../data/lifelong/processed/to_train")
embryo_dir = Path("..data/embryo/processed/to_train")

merged_dfs = merge_embryo_lifelong_files(lifelong_dir, embryo_dir)

output_dir = Path("../data/merged_embryo2life/")
output_dir.mkdir(exist_ok=True, parents=True)

for pattern, df in merged_dfs.items():
    output_name = pattern.replace('DATASET', 'merged') + '.parquet'
    output_path = output_dir / output_name
    df.write_parquet(output_path)

Found 6 matching file pairs

In [ ]:
# load the train_atac_L2k_g11_merged_cpm_l1_q1 file to dataframae
merged_Cpm_l1_q1= pl.read_parquet('../data/merged_embryo2life/train_atac_L2k_g11_merged_cpm_l1_q1__seqs.parquet')
merged_Cpm_l1_q1

shape: (815_358, 149)
┌──────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬──────────┬──────────┐
│ 10_UND   ┆ 10_YSL   ┆ 10_anterio ┆ 10_lateral ┆ … ┆ peak_id    ┆ sequence  ┆ start    ┆ dataset  │
│ ---      ┆ ---      ┆ r/posterio ┆ plate      ┆   ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ f32      ┆ f32      ┆ r axis     ┆ mesoderm   ┆   ┆ str        ┆ str       ┆ i64      ┆ str      │
│          ┆          ┆ ---        ┆ ---        ┆   ┆            ┆           ┆          ┆          │
│          ┆          ┆ f32        ┆ f32        ┆   ┆            ┆           ┆          ┆          │
╞══════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪══════════╪══════════╡
│ 4.517199 ┆ 4.136115 ┆ 2.934742   ┆ 4.235682   ┆ … ┆ 0          ┆ TGCTTTCTC ┆ 10002124 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ATGCAGCAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ ACACGTGTG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAT…      ┆          ┆          │
│ 2.827393 ┆ 2.478875 ┆ 4.424094   ┆ 1.330676   ┆ … ┆ 0          ┆ TAGCTTTTA ┆ 10003707 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ACAATAAAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TAAACAAAC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ AAA…      ┆          ┆          │
│ 4.219712 ┆ 2.478387 ┆ 3.563446   ┆ 3.380321   ┆ … ┆ 0          ┆ TTTCTGCTC ┆ 10004747 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ATAGCTGGA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCCATTTCC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GCT…      ┆          ┆          │
│ 4.133026 ┆ 2.47839  ┆ 4.134303   ┆ 3.507416   ┆ … ┆ 0          ┆ ATCTCTAAT ┆ 10008047 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ AAAGCTGTG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GTACTTAAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TAA…      ┆          ┆          │
│ 2.186927 ┆ 2.478394 ┆ 3.520511   ┆ 1.330678   ┆ … ┆ 0          ┆ CTAACATTT ┆ 10009662 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ GAGCGCTAT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TGAGCACAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ …        ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …        ┆ …        │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56451 ┆ TCTTTATTT ┆ 56451144 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 144-564514 ┆ GAACATTCG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 99         ┆ TCAAGCGAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56452 ┆ ACAGGAGAC ┆ 56452461 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 461-564527 ┆ CACCAGGGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 91         ┆ CAAGAGGAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56454 ┆ CTGATGACC ┆ 56454009 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 009-564545 ┆ TTCTCGGCC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 88         ┆ AATCACAAT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56455 ┆ ATTATGTGT ┆ 56455292 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 292-564556 ┆ GTATTGGGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 10         ┆ TCGGGTCAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GTG…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56457 ┆ TAAACCCTA ┆ 56457510 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 510-564578 ┆ ATGAAGTGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 10         ┆ GTGTGAATG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAC…      ┆          ┆          │
└──────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴──────────┴──────────┘

In [ ]:
merged_Cpm_l1_q0 = pl.read_parquet('../data/merged_embryo2life/train_atac_L2k_g11_merged_cpm_l1_q0__seqs.parquet')
merged_Cpm_l1_q0

shape: (815_358, 149)
┌──────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬──────────┬──────────┐
│ 10_UND   ┆ 10_YSL   ┆ 10_anterio ┆ 10_lateral ┆ … ┆ peak_id    ┆ sequence  ┆ start    ┆ dataset  │
│ ---      ┆ ---      ┆ r/posterio ┆ plate      ┆   ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ r axis     ┆ mesoderm   ┆   ┆ str        ┆ str       ┆ i64      ┆ str      │
│          ┆          ┆ ---        ┆ ---        ┆   ┆            ┆           ┆          ┆          │
│          ┆          ┆ f64        ┆ f64        ┆   ┆            ┆           ┆          ┆          │
╞══════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪══════════╪══════════╡
│ 5.736278 ┆ 4.528056 ┆ 5.269069   ┆ 5.570145   ┆ … ┆ 0          ┆ TGCTTTCTC ┆ 10002124 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ATGCAGCAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ ACACGTGTG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAT…      ┆          ┆          │
│ 4.805037 ┆ 0.0      ┆ 5.682519   ┆ 0.0        ┆ … ┆ 0          ┆ TAGCTTTTA ┆ 10003707 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ACAATAAAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TAAACAAAC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ AAA…      ┆          ┆          │
│ 5.563784 ┆ 0.0      ┆ 5.459051   ┆ 5.276048   ┆ … ┆ 0          ┆ TTTCTGCTC ┆ 10004747 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ATAGCTGGA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCCATTTCC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GCT…      ┆          ┆          │
│ 5.534709 ┆ 0.0      ┆ 5.596153   ┆ 5.336432   ┆ … ┆ 0          ┆ ATCTCTAAT ┆ 10008047 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ AAAGCTGTG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GTACTTAAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TAA…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 5.419276   ┆ 0.0        ┆ … ┆ 0          ┆ CTAACATTT ┆ 10009662 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ GAGCGCTAT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TGAGCACAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ …        ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …        ┆ …        │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56451 ┆ TCTTTATTT ┆ 56451144 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 144-564514 ┆ GAACATTCG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 99         ┆ TCAAGCGAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56452 ┆ ACAGGAGAC ┆ 56452461 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 461-564527 ┆ CACCAGGGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 91         ┆ CAAGAGGAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56454 ┆ CTGATGACC ┆ 56454009 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 009-564545 ┆ TTCTCGGCC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 88         ┆ AATCACAAT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56455 ┆ ATTATGTGT ┆ 56455292 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 292-564556 ┆ GTATTGGGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 10         ┆ TCGGGTCAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GTG…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56457 ┆ TAAACCCTA ┆ 56457510 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 510-564578 ┆ ATGAAGTGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 10         ┆ GTGTGAATG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAC…      ┆          ┆          │
└──────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴──────────┴──────────┘

In [ ]:
embryo_cpm_l1_q1 = pl.read_parquet('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l1_q1__seqs.parquet')
embryo_cpm_l1_q1

shape: (370_058, 73)
┌──────────┬──────────┬────────────┬────────────┬───┬──────────┬──────────┬────────────┬───────────┐
│ 10_UND   ┆ 10_YSL   ┆ 10_anterio ┆ 10_lateral ┆ … ┆ start    ┆ end      ┆ sequence   ┆ Peak      │
│ ---      ┆ ---      ┆ r/posterio ┆ plate      ┆   ┆ ---      ┆ ---      ┆ ---        ┆ ---       │
│ f32      ┆ f32      ┆ r axis     ┆ mesoderm   ┆   ┆ i64      ┆ i64      ┆ str        ┆ str       │
│          ┆          ┆ ---        ┆ ---        ┆   ┆          ┆          ┆            ┆           │
│          ┆          ┆ f32        ┆ f32        ┆   ┆          ┆          ┆            ┆           │
╞══════════╪══════════╪════════════╪════════════╪═══╪══════════╪══════════╪════════════╪═══════════╡
│ 4.517199 ┆ 4.136115 ┆ 2.934742   ┆ 4.235682   ┆ … ┆ 10002124 ┆ 10002624 ┆ TGCTTTCTCA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TGCAGCAAAC ┆ 02124-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ACGTGTGCAT ┆ 02624     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 2.827393 ┆ 2.478875 ┆ 4.424094   ┆ 1.330676   ┆ … ┆ 10003707 ┆ 10004207 ┆ TAGCTTTTAA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CAATAAAATA ┆ 03707-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AACAAACAAA ┆ 04207     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 4.219712 ┆ 2.478387 ┆ 3.563446   ┆ 3.380321   ┆ … ┆ 10004747 ┆ 10005247 ┆ TTTCTGCTCA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TAGCTGGATC ┆ 04747-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CATTTCCGCT ┆ 05247     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 4.133026 ┆ 2.47839  ┆ 4.134303   ┆ 3.507416   ┆ … ┆ 10008047 ┆ 10008547 ┆ ATCTCTAATA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AAGCTGTGGT ┆ 08047-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ACTTAAATAA ┆ 08547     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 2.186927 ┆ 2.478394 ┆ 3.520511   ┆ 1.330678   ┆ … ┆ 10009662 ┆ 10010162 ┆ CTAACATTTG ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AGCGCTATTG ┆ 09662-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AGCACAGTCT ┆ 10162     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ …        ┆ …        ┆ …          ┆ …          ┆ … ┆ …        ┆ …        ┆ …          ┆ …         │
│ 2.186743 ┆ 2.544945 ┆ 2.218797   ┆ 2.026449   ┆ … ┆ 998557   ┆ 999057   ┆ ATATTTCTTG ┆ chr9:9985 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TAAAGGAAAT ┆ 57-999057 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AATAGATTTA ┆           │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 3.486961 ┆ 4.214787 ┆ 3.968464   ┆ 6.336508   ┆ … ┆ 9989556  ┆ 9990056  ┆ GTTTTGGCTT ┆ chr9:9989 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CTTGGTGGCC ┆ 556-99900 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ATTCCTCCAA ┆ 56        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 2.554609 ┆ 2.825087 ┆ 1.976085   ┆ 2.839289   ┆ … ┆ 9992990  ┆ 9993490  ┆ TGAGAGATAT ┆ chr9:9992 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TCTGCAGCAA ┆ 990-99934 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TGACTCCGAC ┆ 90        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 3.77355  ┆ 4.559259 ┆ 2.479997   ┆ 2.014287   ┆ … ┆ 9997607  ┆ 9998107  ┆ TACCCCTGTA ┆ chr9:9997 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CGCAGAACCC ┆ 607-99981 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AAAATAACTG ┆ 07        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 1.662122 ┆ 3.805743 ┆ 2.840032   ┆ 2.845862   ┆ … ┆ 9998460  ┆ 9998960  ┆ TTGGAGAGGA ┆ chr9:9998 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AACCCTCAGC ┆ 460-99989 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ACTGCGGATT ┆ 60        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
└──────────┴──────────┴────────────┴────────────┴───┴──────────┴──────────┴────────────┴───────────┘

In [ ]:
lifelong_cpm_l1_q1 = pl.read_parquet('../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_cpm_l1_q0__seqs.parquet')
lifelong_cpm_l1_q1

shape: (445_300, 79)
┌──────────┬────────────┬────────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ 14_teeth ┆ 14_dermal  ┆ 14_perivas ┆ 14_perios ┆ … ┆ start    ┆ end      ┆ sequence  ┆ peak_id   │
│ ---      ┆ fibroblast ┆ cular      ┆ teum/tend ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---       │
│ f32      ┆ ---        ┆ ---        ┆ on/ligame ┆   ┆ i64      ┆ i64      ┆ str       ┆ str       │
│          ┆ f32        ┆ f32        ┆ nt        ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆            ┆ ---       ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆            ┆ f32       ┆   ┆          ┆          ┆           ┆           │
╞══════════╪════════════╪════════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 0.268178 ┆ 0.336311   ┆ 0.202148   ┆ 0.201847  ┆ … ┆ 1168     ┆ 1395     ┆ TCAAAGAGC ┆ chr1-1168 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TGTTGCAGC ┆ -1395     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ ATGAGTGGA ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AAA…      ┆           │
│ 0.352856 ┆ 0.39649    ┆ 0.243614   ┆ 0.394681  ┆ … ┆ 3061     ┆ 3345     ┆ TCTGGGTTA ┆ chr1-3061 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAAGTTTTA ┆ -3345     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GAAGAATTA ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ ATA…      ┆           │
│ 0.279919 ┆ 0.076414   ┆ 0.373467   ┆ 0.182398  ┆ … ┆ 4198     ┆ 4561     ┆ AATGACTCA ┆ chr1-4198 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TTAGTATTC ┆ -4561     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTGTTTTTG ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GAC…      ┆           │
│ 1.264823 ┆ 1.21621    ┆ 0.791955   ┆ 1.022334  ┆ … ┆ 5995     ┆ 6563     ┆ TCAGGTGTG ┆ chr1-5995 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AATGCTGTT ┆ -6563     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TTCTGTTTC ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AAA…      ┆           │
│ 2.694029 ┆ 2.792791   ┆ 2.745074   ┆ 2.687598  ┆ … ┆ 11183    ┆ 12718    ┆ TTGAACTGA ┆ chr1-1118 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AAATCGTTT ┆ 3-12718   │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TGAATAGTC ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTG…      ┆           │
│ …        ┆ …          ┆ …          ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ 0.257151 ┆ 0.188159   ┆ 0.486144   ┆ 0.486241  ┆ … ┆ 56451144 ┆ 56451499 ┆ TCTTTATTT ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GAACATTCG ┆ 1144-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCAAGCGAG ┆ 1499      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCT…      ┆           │
│ 0.551813 ┆ 0.0        ┆ 0.306954   ┆ 0.294547  ┆ … ┆ 56452461 ┆ 56452791 ┆ ACAGGAGAC ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CACCAGGGT ┆ 2461-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAAGAGGAG ┆ 2791      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCT…      ┆           │
│ 0.986643 ┆ 0.551549   ┆ 0.727792   ┆ 0.694573  ┆ … ┆ 56454009 ┆ 56454588 ┆ CTGATGACC ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TTCTCGGCC ┆ 4009-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AATCACAAT ┆ 4588      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAT…      ┆           │
│ 0.209463 ┆ 0.268585   ┆ 0.488721   ┆ 0.214531  ┆ … ┆ 56455292 ┆ 56455610 ┆ ATTATGTGT ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTATTGGGT ┆ 5292-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCGGGTCAG ┆ 5610      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTG…      ┆           │
│ 0.0      ┆ 0.561268   ┆ 0.075037   ┆ 0.533701  ┆ … ┆ 56457510 ┆ 56457810 ┆ TAAACCCTA ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ ATGAAGTGT ┆ 7510-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTGTGAATG ┆ 7810      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAC…      ┆           │
└──────────┴────────────┴────────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [ ]:
# create training data for **EMBRYO**
out_embryo_dir = prepare_training_from_df(
    df=embryo_cpm_l1_q1,
    pattern="train_atac_L2k_g11_embryo_cpm_l1_q1__seqs",
    output_dir="../data/embryo/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        # or "random"
    holdout_chroms=None,            # or a list of specified ["1","2"] 
    channel_first=True
)
print("Saved to:", out_embryo_dir)

# create training data for **LIFELONG**
out_lifelong_dir = prepare_training_from_df(
    df=lifelong_cpm_l1_q1,
    pattern="train_atac_L2k_g11_lifelong_cpm_l1_q1__seqs",
    output_dir="../data/lifelong/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        
    holdout_chroms=None,       
    channel_first=True
)
print("Saved to:", out_lifelong_dir)


# create training data for **EMBRYO + LIFELONG**
out_merged_dir = prepare_training_from_df(
    df=merged_Cpm_l1_q1,
    pattern="train_atac_L2k_g11_merged_cpm_l1_q1__seqs",
    output_dir="../data/merged_embryo2life/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        
    holdout_chroms=None,            
    channel_first=True
)
print("Saved to:", out_merged_dir)

# bundle = load_split_folder(out_dir)
# bundle["X_train"].shape, bundle["Y_train"].shape, bundle["meta"]

Saved to: ../../data/lifelong/training/train_atac_L2k_g11_lifelong_cpm_l1_q1__seqs/80_20_chrom_split
Saved to: ../../data/merged_embryo2life/training/train_atac_L2k_g11_merged_cpm_l1_q1__seqs/80_20_chrom_split

## Multiome

In [9]:
import anndata as ad
multiome_data = ad.read_h5ad(
    "../data/multiome/zf_multiome_atlas_full_ATAC_v1_release.h5ad"
)
multiome_data

AnnData object with n_obs × n_vars = 94562 × 640834
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'nCount_ATAC', 'nFeature_ATAC', 'nucleosome_signal', 'nucleosome_percentile', 'TSS.enrichment', 'TSS.percentile', 'nCount_SCT', 'nFeature_SCT', 'global_annotation', 'nCount_peaks_bulk', 'nFeature_peaks_bulk', 'nCount_peaks_celltype', 'nFeature_peaks_celltype', 'nCount_peaks_merged', 'nFeature_peaks_merged', 'SCT.weight', 'peaks_merged.weight', 'nCount_Gene.Activity', 'nFeature_Gene.Activity', 'nCount_peaks_integrated', 'nFeature_peaks_integrated', 'dataset', 'integrated.weight', 'peaks_integrated.weight', 'wsnn_res.0.8', 'seurat_clusters', 'leiden_0.5', 'leiden_0.8', 'leiden_1', 'leiden_1.2', 'leiden_1.5', 'leiden_2', 'leiden_3', 'leiden_4', 'leiden_5', 'leiden_6', 'leiden_7', 'leiden_8', 'leiden_9', 'leiden_10', 'leiden_0.5_merged', 'leiden_0.8_merged', 'leiden_1_merged', 'leiden_1.2_merged', 'leiden_1.5_merged', 'leiden_2_merged', 'leiden_3_merged', 'leiden_4_merged', 'leiden_5_merged', 'leiden_6_merged', 'leiden_7_merged', 'leiden_8_merged', 'leiden_9_merged', 'leiden_10_merged', 'annotation_ML_coarse', 'dev_stage'
    layers: 'counts'

In [ ]:
celltype_col = "annotation_ML_coarse"  #

import scipy.sparse as sp

adata = multiome_data  # your AnnData object

# choose counts matrix
counts = adata.layers["counts"] if "counts" in adata.layers else adata.X

# cell type labels
labels = adata.obs[celltype_col].astype("category")
categories = labels.cat.categories
codes = labels.cat.codes.to_numpy()

# design matrix: cells × celltypes (one-hot)
row = np.arange(adata.n_obs)
col = codes
data = np.ones(adata.n_obs, dtype=np.int8)
design = sp.csr_matrix((data, (row, col)), shape=(adata.n_obs, len(categories)))

# pseudobulk: (celltypes × cells) @ (cells × peaks) → (celltypes × peaks)
pseudobulk = design.T @ counts  # shape: (n_celltypes, n_peaks)

print("pseudobulk shape:", pseudobulk.shape)
# (num_celltypes, num_peaks)

pseudobulk shape: (32, 640834)

In [41]:
# convert to pandas DataFrame (be careful, may be huge!)
pb_df = pd.DataFrame(
    pseudobulk.toarray().T,     # transpose so peaks = rows
    index=adata.var_names,      # peaks
    columns=categories          # celltypes
)

pb_df.iloc[:5, :5]  # preview

             NMPs   PSM  differentiating_neurons  endocrine_pancreas  endoderm
1-32-526       11    28                       14                  12        12
1-2372-3057    17    52                       26                  32        22
1-3427-4032    55   154                       62                  77        34
1-4469-7268   670  1999                      371                 893       491
1-9541-9969   152   493                       80                 179       115

In [30]:
import pandas as pd
import scipy.sparse as sp

label_col = "annotation_ML_coarse"  # or "global_annotation"
labels = adata.obs[label_col].astype("category")
counts = adata.layers["counts"] if "counts" in adata.layers else adata.X

# Build a sparse design matrix: cells × celltypes
cats = labels.cat.categories
row = np.arange(adata.n_obs)
col = labels.cat.codes.values
data = np.ones(adata.n_obs, dtype=np.int8)
D = sp.csr_matrix((data, (row, col)), shape=(adata.n_obs, len(cats)))

# Pseudobulk: (celltypes × cells) @ (cells × peaks) = celltypes × peaks
PB = D.T @ counts  # sparse × sparse -> sparse

print("pseudobulk shape:", PB.shape)  # (#celltypes, #peaks)
celltypes = np.array(cats)
peaks = np.array(adata.var_names)

pseudobulk shape: (32, 640834)