In [8]:
import polars as pl 
import pandas as pd
import os
import pandas as pd
import scipy.sparse as sp
import numpy as np
from pathlib import Path
import re
import sys
from zebra_dev.utils import preprocess, plotting, training 
from zebra_dev.models import dilated_baseline_model

lifelong_dir = Path("../data/lifelong/processed/to_train")
embryo_dir = Path("../data/embryo/processed/to_train")

lifelong_files = sorted(lifelong_dir.glob("*.parquet"))
embryo_files = sorted(embryo_dir.glob("*.parquet"))

print(lifelong_files)
print(embryo_files)

[PosixPath('../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_cpm_l0_q0__seqs.parquet'), PosixPath('../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_cpm_l1_q0__seqs.parquet'), PosixPath('../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_cpm_l1_q1__seqs.parquet'), PosixPath('../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_raw_l0_q0__seqs.parquet'), PosixPath('../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_raw_l1_q0__seqs.parquet'), PosixPath('../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_raw_l1_q1__seqs.parquet')]
[PosixPath('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l0_q0__seqs.parquet'), PosixPath('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l0_q1__seqs.parquet'), PosixPath('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l1_q0__seqs.parquet'), PosixPath('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l1_q1__seqs.parquet'), PosixPath('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_raw_l0_q0__seqs.parquet'), PosixPath('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_raw_l0_q1__seqs.parquet'), PosixPath('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_raw_l1_q0__seqs.parquet'), PosixPath('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_raw_l1_q1__seqs.parquet')]

In [4]:
lifelong_dfs = [pl.read_parquet(f) for f in lifelong_files]
embryo_dfs   = [pl.read_parquet(f) for f in embryo_files]

In [3]:
lifelong_dir = Path("../data/lifelong/processed/to_train")
embryo_dir = Path("..data/embryo/processed/to_train")

merged_dfs = preprocess.merge_embryo_lifelong_files(lifelong_dir, embryo_dir)

output_dir = Path("../data/merged_embryo2life/")
output_dir.mkdir(exist_ok=True, parents=True)

for pattern, df in merged_dfs.items():
    output_name = pattern.replace('DATASET', 'merged') + '.parquet'
    output_path = output_dir / output_name
    df.write_parquet(output_path)

Found 0 matching file pairs

In [4]:
# load the train_atac_L2k_g11_merged_cpm_l1_q1 file to dataframae
merged_Cpm_l1_q1= pl.read_parquet('../data/merged_embryo2life/train_atac_L2k_g11_merged_cpm_l1_q1__seqs.parquet')
merged_Cpm_l1_q1

shape: (815_358, 149)
┌──────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬──────────┬──────────┐
│ 10_UND   ┆ 10_YSL   ┆ 10_anterio ┆ 10_lateral ┆ … ┆ peak_id    ┆ sequence  ┆ start    ┆ dataset  │
│ ---      ┆ ---      ┆ r/posterio ┆ plate      ┆   ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ f32      ┆ f32      ┆ r axis     ┆ mesoderm   ┆   ┆ str        ┆ str       ┆ i64      ┆ str      │
│          ┆          ┆ ---        ┆ ---        ┆   ┆            ┆           ┆          ┆          │
│          ┆          ┆ f32        ┆ f32        ┆   ┆            ┆           ┆          ┆          │
╞══════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪══════════╪══════════╡
│ 4.517199 ┆ 4.136115 ┆ 2.934742   ┆ 4.235682   ┆ … ┆ 0          ┆ TGCTTTCTC ┆ 10002124 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ATGCAGCAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ ACACGTGTG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAT…      ┆          ┆          │
│ 2.827393 ┆ 2.478875 ┆ 4.424094   ┆ 1.330676   ┆ … ┆ 0          ┆ TAGCTTTTA ┆ 10003707 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ACAATAAAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TAAACAAAC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ AAA…      ┆          ┆          │
│ 4.219712 ┆ 2.478387 ┆ 3.563446   ┆ 3.380321   ┆ … ┆ 0          ┆ TTTCTGCTC ┆ 10004747 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ATAGCTGGA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCCATTTCC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GCT…      ┆          ┆          │
│ 4.133026 ┆ 2.47839  ┆ 4.134303   ┆ 3.507416   ┆ … ┆ 0          ┆ ATCTCTAAT ┆ 10008047 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ AAAGCTGTG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GTACTTAAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TAA…      ┆          ┆          │
│ 2.186927 ┆ 2.478394 ┆ 3.520511   ┆ 1.330678   ┆ … ┆ 0          ┆ CTAACATTT ┆ 10009662 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ GAGCGCTAT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TGAGCACAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ …        ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …        ┆ …        │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56451 ┆ TCTTTATTT ┆ 56451144 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 144-564514 ┆ GAACATTCG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 99         ┆ TCAAGCGAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56452 ┆ ACAGGAGAC ┆ 56452461 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 461-564527 ┆ CACCAGGGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 91         ┆ CAAGAGGAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56454 ┆ CTGATGACC ┆ 56454009 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 009-564545 ┆ TTCTCGGCC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 88         ┆ AATCACAAT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56455 ┆ ATTATGTGT ┆ 56455292 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 292-564556 ┆ GTATTGGGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 10         ┆ TCGGGTCAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GTG…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56457 ┆ TAAACCCTA ┆ 56457510 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 510-564578 ┆ ATGAAGTGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 10         ┆ GTGTGAATG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAC…      ┆          ┆          │
└──────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴──────────┴──────────┘

In [4]:
merged_Cpm_l1_q0 = pl.read_parquet('../data/merged_embryo2life/train_atac_L2k_g11_merged_cpm_l1_q0__seqs.parquet')
merged_Cpm_l1_q0

shape: (815_358, 149)
┌──────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬──────────┬──────────┐
│ 10_UND   ┆ 10_YSL   ┆ 10_anterio ┆ 10_lateral ┆ … ┆ peak_id    ┆ sequence  ┆ start    ┆ dataset  │
│ ---      ┆ ---      ┆ r/posterio ┆ plate      ┆   ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ r axis     ┆ mesoderm   ┆   ┆ str        ┆ str       ┆ i64      ┆ str      │
│          ┆          ┆ ---        ┆ ---        ┆   ┆            ┆           ┆          ┆          │
│          ┆          ┆ f64        ┆ f64        ┆   ┆            ┆           ┆          ┆          │
╞══════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪══════════╪══════════╡
│ 5.736278 ┆ 4.528056 ┆ 5.269069   ┆ 5.570145   ┆ … ┆ 0          ┆ TGCTTTCTC ┆ 10002124 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ATGCAGCAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ ACACGTGTG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAT…      ┆          ┆          │
│ 4.805037 ┆ 0.0      ┆ 5.682519   ┆ 0.0        ┆ … ┆ 0          ┆ TAGCTTTTA ┆ 10003707 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ACAATAAAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TAAACAAAC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ AAA…      ┆          ┆          │
│ 5.563784 ┆ 0.0      ┆ 5.459051   ┆ 5.276048   ┆ … ┆ 0          ┆ TTTCTGCTC ┆ 10004747 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ ATAGCTGGA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCCATTTCC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GCT…      ┆          ┆          │
│ 5.534709 ┆ 0.0      ┆ 5.596153   ┆ 5.336432   ┆ … ┆ 0          ┆ ATCTCTAAT ┆ 10008047 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ AAAGCTGTG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GTACTTAAA ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TAA…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 5.419276   ┆ 0.0        ┆ … ┆ 0          ┆ CTAACATTT ┆ 10009662 ┆ embryo   │
│          ┆          ┆            ┆            ┆   ┆            ┆ GAGCGCTAT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TGAGCACAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ …        ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …        ┆ …        │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56451 ┆ TCTTTATTT ┆ 56451144 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 144-564514 ┆ GAACATTCG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 99         ┆ TCAAGCGAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56452 ┆ ACAGGAGAC ┆ 56452461 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 461-564527 ┆ CACCAGGGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 91         ┆ CAAGAGGAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ TCT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56454 ┆ CTGATGACC ┆ 56454009 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 009-564545 ┆ TTCTCGGCC ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 88         ┆ AATCACAAT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAT…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56455 ┆ ATTATGTGT ┆ 56455292 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 292-564556 ┆ GTATTGGGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 10         ┆ TCGGGTCAG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ GTG…      ┆          ┆          │
│ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ … ┆ chr9-56457 ┆ TAAACCCTA ┆ 56457510 ┆ lifelong │
│          ┆          ┆            ┆            ┆   ┆ 510-564578 ┆ ATGAAGTGT ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆ 10         ┆ GTGTGAATG ┆          ┆          │
│          ┆          ┆            ┆            ┆   ┆            ┆ CAC…      ┆          ┆          │
└──────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴──────────┴──────────┘

In [5]:
embryo_cpm_l1_q1 = pl.read_parquet('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l1_q1__seqs.parquet')
embryo_cpm_l1_q1

shape: (370_058, 73)
┌──────────┬──────────┬────────────┬────────────┬───┬──────────┬──────────┬────────────┬───────────┐
│ 10_UND   ┆ 10_YSL   ┆ 10_anterio ┆ 10_lateral ┆ … ┆ start    ┆ end      ┆ sequence   ┆ Peak      │
│ ---      ┆ ---      ┆ r/posterio ┆ plate      ┆   ┆ ---      ┆ ---      ┆ ---        ┆ ---       │
│ f32      ┆ f32      ┆ r axis     ┆ mesoderm   ┆   ┆ i64      ┆ i64      ┆ str        ┆ str       │
│          ┆          ┆ ---        ┆ ---        ┆   ┆          ┆          ┆            ┆           │
│          ┆          ┆ f32        ┆ f32        ┆   ┆          ┆          ┆            ┆           │
╞══════════╪══════════╪════════════╪════════════╪═══╪══════════╪══════════╪════════════╪═══════════╡
│ 4.517199 ┆ 4.136115 ┆ 2.934742   ┆ 4.235682   ┆ … ┆ 10002124 ┆ 10002624 ┆ TGCTTTCTCA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TGCAGCAAAC ┆ 02124-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ACGTGTGCAT ┆ 02624     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 2.827393 ┆ 2.478875 ┆ 4.424094   ┆ 1.330676   ┆ … ┆ 10003707 ┆ 10004207 ┆ TAGCTTTTAA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CAATAAAATA ┆ 03707-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AACAAACAAA ┆ 04207     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 4.219712 ┆ 2.478387 ┆ 3.563446   ┆ 3.380321   ┆ … ┆ 10004747 ┆ 10005247 ┆ TTTCTGCTCA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TAGCTGGATC ┆ 04747-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CATTTCCGCT ┆ 05247     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 4.133026 ┆ 2.47839  ┆ 4.134303   ┆ 3.507416   ┆ … ┆ 10008047 ┆ 10008547 ┆ ATCTCTAATA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AAGCTGTGGT ┆ 08047-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ACTTAAATAA ┆ 08547     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 2.186927 ┆ 2.478394 ┆ 3.520511   ┆ 1.330678   ┆ … ┆ 10009662 ┆ 10010162 ┆ CTAACATTTG ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AGCGCTATTG ┆ 09662-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AGCACAGTCT ┆ 10162     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ …        ┆ …        ┆ …          ┆ …          ┆ … ┆ …        ┆ …        ┆ …          ┆ …         │
│ 2.186743 ┆ 2.544945 ┆ 2.218797   ┆ 2.026449   ┆ … ┆ 998557   ┆ 999057   ┆ ATATTTCTTG ┆ chr9:9985 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TAAAGGAAAT ┆ 57-999057 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AATAGATTTA ┆           │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 3.486961 ┆ 4.214787 ┆ 3.968464   ┆ 6.336508   ┆ … ┆ 9989556  ┆ 9990056  ┆ GTTTTGGCTT ┆ chr9:9989 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CTTGGTGGCC ┆ 556-99900 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ATTCCTCCAA ┆ 56        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 2.554609 ┆ 2.825087 ┆ 1.976085   ┆ 2.839289   ┆ … ┆ 9992990  ┆ 9993490  ┆ TGAGAGATAT ┆ chr9:9992 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TCTGCAGCAA ┆ 990-99934 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TGACTCCGAC ┆ 90        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 3.77355  ┆ 4.559259 ┆ 2.479997   ┆ 2.014287   ┆ … ┆ 9997607  ┆ 9998107  ┆ TACCCCTGTA ┆ chr9:9997 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CGCAGAACCC ┆ 607-99981 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AAAATAACTG ┆ 07        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 1.662122 ┆ 3.805743 ┆ 2.840032   ┆ 2.845862   ┆ … ┆ 9998460  ┆ 9998960  ┆ TTGGAGAGGA ┆ chr9:9998 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AACCCTCAGC ┆ 460-99989 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ACTGCGGATT ┆ 60        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
└──────────┴──────────┴────────────┴────────────┴───┴──────────┴──────────┴────────────┴───────────┘

In [6]:
embryo_cpm_l0_q0= pl.read_parquet('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l0_q0__seqs.parquet')
embryo_cpm_l0_q0

shape: (370_058, 73)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ 10_UND     ┆ 10_YSL    ┆ 10_anteri ┆ 10_latera ┆ … ┆ start    ┆ end      ┆ sequence  ┆ Peak      │
│ ---        ┆ ---       ┆ or/poster ┆ l plate   ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---       │
│ f64        ┆ f64       ┆ ior axis  ┆ mesoderm  ┆   ┆ i64      ┆ i64      ┆ str       ┆ str       │
│            ┆           ┆ ---       ┆ ---       ┆   ┆          ┆          ┆           ┆           │
│            ┆           ┆ f64       ┆ f64       ┆   ┆          ┆          ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 308.908779 ┆ 91.578373 ┆ 193.23495 ┆ 261.47208 ┆ … ┆ 10002124 ┆ 10002624 ┆ TGCTTTCTC ┆ chr10:100 │
│            ┆           ┆ 6         ┆ 8         ┆   ┆          ┆          ┆ ATGCAGCAA ┆ 02124-100 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ ACACGTGTG ┆ 02624     │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ CAT…      ┆           │
│ 121.124031 ┆ 0.0       ┆ 292.68829 ┆ 0.0       ┆ … ┆ 10003707 ┆ 10004207 ┆ TAGCTTTTA ┆ chr10:100 │
│            ┆           ┆ 2         ┆           ┆   ┆          ┆          ┆ ACAATAAAA ┆ 03707-100 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TAAACAAAC ┆ 04207     │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ AAA…      ┆           │
│ 259.807742 ┆ 0.0       ┆ 233.87433 ┆ 194.59539 ┆ … ┆ 10004747 ┆ 10005247 ┆ TTTCTGCTC ┆ chr10:100 │
│            ┆           ┆ 3         ┆ 5         ┆   ┆          ┆          ┆ ATAGCTGGA ┆ 04747-100 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TCCATTTCC ┆ 05247     │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ GCT…      ┆           │
│ 252.33409  ┆ 0.0       ┆ 268.38800 ┆ 206.77006 ┆ … ┆ 10008047 ┆ 10008547 ┆ ATCTCTAAT ┆ chr10:100 │
│            ┆           ┆ 6         ┆ 4         ┆   ┆          ┆          ┆ AAAGCTGTG ┆ 08047-100 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ GTACTTAAA ┆ 08547     │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TAA…      ┆           │
│ 0.0        ┆ 0.0       ┆ 224.71569 ┆ 0.0       ┆ … ┆ 10009662 ┆ 10010162 ┆ CTAACATTT ┆ chr10:100 │
│            ┆           ┆ 5         ┆           ┆   ┆          ┆          ┆ GAGCGCTAT ┆ 09662-100 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TGAGCACAG ┆ 10162     │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TCT…      ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ 0.0        ┆ 21.947151 ┆ 148.27097 ┆ 91.701055 ┆ … ┆ 998557   ┆ 999057   ┆ ATATTTCTT ┆ chr9:9985 │
│            ┆           ┆ 2         ┆           ┆   ┆          ┆          ┆ GTAAAGGAA ┆ 57-999057 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ ATAATAGAT ┆           │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TTA…      ┆           │
│ 183.452578 ┆ 93.641831 ┆ 252.67457 ┆ 583.09037 ┆ … ┆ 9989556  ┆ 9990056  ┆ GTTTTGGCT ┆ chr9:9989 │
│            ┆           ┆ 7         ┆ 9         ┆   ┆          ┆          ┆ TCTTGGTGG ┆ 556-99900 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ CCATTCCTC ┆ 56        │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ CAA…      ┆           │
│ 80.279372  ┆ 41.451003 ┆ 102.19724 ┆ 168.18028 ┆ … ┆ 9992990  ┆ 9993490  ┆ TGAGAGATA ┆ chr9:9992 │
│            ┆           ┆ 1         ┆ 9         ┆   ┆          ┆          ┆ TTCTGCAGC ┆ 990-99934 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ AATGACTCC ┆ 90        │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ GAC…      ┆           │
│ 215.666895 ┆ 115.94308 ┆ 160.82318 ┆ 84.997875 ┆ … ┆ 9997607  ┆ 9998107  ┆ TACCCCTGT ┆ chr9:9997 │
│            ┆ 9         ┆ 8         ┆           ┆   ┆          ┆          ┆ ACGCAGAAC ┆ 607-99981 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ CCAAAATAA ┆ 07        │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ CTG…      ┆           │
│ 0.0        ┆ 79.185968 ┆ 184.53589 ┆ 169.81957 ┆ … ┆ 9998460  ┆ 9998960  ┆ TTGGAGAGG ┆ chr9:9998 │
│            ┆           ┆ 2         ┆ 4         ┆   ┆          ┆          ┆ AAACCCTCA ┆ 460-99989 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ GCACTGCGG ┆ 60        │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ ATT…      ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [7]:
embryo_cpm_l1_q0= pl.read_parquet('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l1_q0__seqs.parquet')
embryo_cpm_l1_q0

shape: (370_058, 73)
┌──────────┬──────────┬────────────┬────────────┬───┬──────────┬──────────┬────────────┬───────────┐
│ 10_UND   ┆ 10_YSL   ┆ 10_anterio ┆ 10_lateral ┆ … ┆ start    ┆ end      ┆ sequence   ┆ Peak      │
│ ---      ┆ ---      ┆ r/posterio ┆ plate      ┆   ┆ ---      ┆ ---      ┆ ---        ┆ ---       │
│ f64      ┆ f64      ┆ r axis     ┆ mesoderm   ┆   ┆ i64      ┆ i64      ┆ str        ┆ str       │
│          ┆          ┆ ---        ┆ ---        ┆   ┆          ┆          ┆            ┆           │
│          ┆          ┆ f64        ┆ f64        ┆   ┆          ┆          ┆            ┆           │
╞══════════╪══════════╪════════════╪════════════╪═══╪══════════╪══════════╪════════════╪═══════════╡
│ 5.736278 ┆ 4.528056 ┆ 5.269069   ┆ 5.570145   ┆ … ┆ 10002124 ┆ 10002624 ┆ TGCTTTCTCA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TGCAGCAAAC ┆ 02124-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ACGTGTGCAT ┆ 02624     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 4.805037 ┆ 0.0      ┆ 5.682519   ┆ 0.0        ┆ … ┆ 10003707 ┆ 10004207 ┆ TAGCTTTTAA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CAATAAAATA ┆ 03707-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AACAAACAAA ┆ 04207     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 5.563784 ┆ 0.0      ┆ 5.459051   ┆ 5.276048   ┆ … ┆ 10004747 ┆ 10005247 ┆ TTTCTGCTCA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TAGCTGGATC ┆ 04747-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CATTTCCGCT ┆ 05247     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 5.534709 ┆ 0.0      ┆ 5.596153   ┆ 5.336432   ┆ … ┆ 10008047 ┆ 10008547 ┆ ATCTCTAATA ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AAGCTGTGGT ┆ 08047-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ACTTAAATAA ┆ 08547     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 0.0      ┆ 0.0      ┆ 5.419276   ┆ 0.0        ┆ … ┆ 10009662 ┆ 10010162 ┆ CTAACATTTG ┆ chr10:100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AGCGCTATTG ┆ 09662-100 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AGCACAGTCT ┆ 10162     │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ …        ┆ …        ┆ …          ┆ …          ┆ … ┆ …        ┆ …        ┆ …          ┆ …         │
│ 0.0      ┆ 3.133194 ┆ 5.005763   ┆ 4.52938    ┆ … ┆ 998557   ┆ 999057   ┆ ATATTTCTTG ┆ chr9:9985 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TAAAGGAAAT ┆ 57-999057 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AATAGATTTA ┆           │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 5.217392 ┆ 4.5501   ┆ 5.536052   ┆ 6.370056   ┆ … ┆ 9989556  ┆ 9990056  ┆ GTTTTGGCTT ┆ chr9:9989 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CTTGGTGGCC ┆ 556-99900 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ATTCCTCCAA ┆ 56        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 4.397892 ┆ 3.748351 ┆ 4.636642   ┆ 5.130965   ┆ … ┆ 9992990  ┆ 9993490  ┆ TGAGAGATAT ┆ chr9:9992 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TCTGCAGCAA ┆ 990-99934 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ TGACTCCGAC ┆ 90        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 5.378361 ┆ 4.761687 ┆ 5.086504   ┆ 4.454323   ┆ … ┆ 9997607  ┆ 9998107  ┆ TACCCCTGTA ┆ chr9:9997 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ CGCAGAACCC ┆ 607-99981 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AAAATAACTG ┆ 07        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
│ 0.0      ┆ 4.384349 ┆ 5.223248   ┆ 5.140608   ┆ … ┆ 9998460  ┆ 9998960  ┆ TTGGAGAGGA ┆ chr9:9998 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ AACCCTCAGC ┆ 460-99989 │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ ACTGCGGATT ┆ 60        │
│          ┆          ┆            ┆            ┆   ┆          ┆          ┆ …          ┆           │
└──────────┴──────────┴────────────┴────────────┴───┴──────────┴──────────┴────────────┴───────────┘

In [8]:
embryo_cpm_l0_q1= pl.read_parquet('../data/embryo/processed/to_train/train_atac_L2k_g11_embryo_cpm_l0_q1__seqs.parquet')
embryo_cpm_l0_q1

shape: (370_058, 73)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ 10_UND     ┆ 10_YSL    ┆ 10_anteri ┆ 10_latera ┆ … ┆ start    ┆ end      ┆ sequence  ┆ Peak      │
│ ---        ┆ ---       ┆ or/poster ┆ l plate   ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---       │
│ f32        ┆ f32       ┆ ior axis  ┆ mesoderm  ┆   ┆ i64      ┆ i64      ┆ str       ┆ str       │
│            ┆           ┆ ---       ┆ ---       ┆   ┆          ┆          ┆           ┆           │
│            ┆           ┆ f32       ┆ f32       ┆   ┆          ┆          ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 227.962051 ┆ 181.65477 ┆ 103.51621 ┆ 190.99868 ┆ … ┆ 10002124 ┆ 10002624 ┆ TGCTTTCTC ┆ chr10:100 │
│            ┆           ┆ 2         ┆ 8         ┆   ┆          ┆          ┆ ATGCAGCAA ┆ 02124-100 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ ACACGTGTG ┆ 02624     │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ CAT…      ┆           │
│ 95.616241  ┆ 79.235184 ┆ 208.57495 ┆ 36.067772 ┆ … ┆ 10003707 ┆ 10004207 ┆ TAGCTTTTA ┆ chr10:100 │
│            ┆           ┆ 1         ┆           ┆   ┆          ┆          ┆ ACAATAAAA ┆ 03707-100 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TAAACAAAC ┆ 04207     │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ AAA…      ┆           │
│ 187.574112 ┆ 79.178749 ┆ 140.99704 ┆ 121.03050 ┆ … ┆ 10004747 ┆ 10005247 ┆ TTTCTGCTC ┆ chr10:100 │
│            ┆           ┆           ┆ 2         ┆   ┆          ┆          ┆ ATAGCTGGA ┆ 04747-100 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TCCATTTCC ┆ 05247     │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ GCT…      ┆           │
│ 181.011124 ┆ 79.179443 ┆ 181.27638 ┆ 131.62420 ┆ … ┆ 10008047 ┆ 10008547 ┆ ATCTCTAAT ┆ chr10:100 │
│            ┆           ┆ 2         ┆ 7         ┆   ┆          ┆          ┆ AAAGCTGTG ┆ 08047-100 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ GTACTTAAA ┆ 08547     │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TAA…      ┆           │
│ 67.077049  ┆ 79.180061 ┆ 133.71673 ┆ 36.068043 ┆ … ┆ 10009662 ┆ 10010162 ┆ CTAACATTT ┆ chr10:100 │
│            ┆           ┆ 6         ┆           ┆   ┆          ┆          ┆ GAGCGCTAT ┆ 09662-100 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TGAGCACAG ┆ 10162     │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TCT…      ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ 67.05687   ┆ 81.259354 ┆ 71.338219 ┆ 60.323235 ┆ … ┆ 998557   ┆ 999057   ┆ ATATTTCTT ┆ chr9:9985 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ GTAAAGGAA ┆ 57-999057 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ ATAATAGAT ┆           │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TTA…      ┆           │
│ 128.560822 ┆ 186.65200 ┆ 162.93141 ┆ 610.21673 ┆ … ┆ 9989556  ┆ 9990056  ┆ GTTTTGGCT ┆ chr9:9989 │
│            ┆ 8         ┆ 2         ┆ 6         ┆   ┆          ┆          ┆ TCTTGGTGG ┆ 556-99900 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ CCATTCCTC ┆ 56        │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ CAA…      ┆           │
│ 82.18055   ┆ 95.299294 ┆ 54.726086 ┆ 97.307785 ┆ … ┆ 9992990  ┆ 9993490  ┆ TGAGAGATA ┆ chr9:9992 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ TTCTGCAGC ┆ 990-99934 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ AATGACTCC ┆ 90        │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ GAC…      ┆           │
│ 148.517761 ┆ 239.48533 ┆ 79.363869 ┆ 58.766132 ┆ … ┆ 9997607  ┆ 9998107  ┆ TACCCCTGT ┆ chr9:9997 │
│            ┆ 6         ┆           ┆           ┆   ┆          ┆          ┆ ACGCAGAAC ┆ 607-99981 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ CCAAAATAA ┆ 07        │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ CTG…      ┆           │
│ 43.379715  ┆ 152.94551 ┆ 97.417686 ┆ 98.285545 ┆ … ┆ 9998460  ┆ 9998960  ┆ TTGGAGAGG ┆ chr9:9998 │
│            ┆ 1         ┆           ┆           ┆   ┆          ┆          ┆ AAACCCTCA ┆ 460-99989 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ GCACTGCGG ┆ 60        │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ ATT…      ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [7]:
lifelong_cpm_l1_q1 = pl.read_parquet('../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_cpm_l1_q1__seqs.parquet')
lifelong_cpm_l1_q1

shape: (445_300, 79)
┌──────────┬────────────┬────────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ 14_teeth ┆ 14_dermal  ┆ 14_perivas ┆ 14_perios ┆ … ┆ start    ┆ end      ┆ sequence  ┆ peak_id   │
│ ---      ┆ fibroblast ┆ cular      ┆ teum/tend ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---       │
│ f32      ┆ ---        ┆ ---        ┆ on/ligame ┆   ┆ i64      ┆ i64      ┆ str       ┆ str       │
│          ┆ f32        ┆ f32        ┆ nt        ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆            ┆ ---       ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆            ┆ f32       ┆   ┆          ┆          ┆           ┆           │
╞══════════╪════════════╪════════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 0.168097 ┆ 0.260924   ┆ 0.097243   ┆ 0.094158  ┆ … ┆ 1168     ┆ 1395     ┆ TCAAAGAGC ┆ chr1-1168 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TGTTGCAGC ┆ -1395     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ ATGAGTGGA ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AAA…      ┆           │
│ 0.25792  ┆ 0.328231   ┆ 0.127745   ┆ 0.306451  ┆ … ┆ 3061     ┆ 3345     ┆ TCTGGGTTA ┆ chr1-3061 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAAGTTTTA ┆ -3345     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GAAGAATTA ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ ATA…      ┆           │
│ 0.180822 ┆ 0.037679   ┆ 0.260638   ┆ 0.073737  ┆ … ┆ 4198     ┆ 4561     ┆ AATGACTCA ┆ chr1-4198 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TTAGTATTC ┆ -4561     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTGTTTTTG ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GAC…      ┆           │
│ 1.220496 ┆ 1.173946   ┆ 0.770668   ┆ 1.00503   ┆ … ┆ 5995     ┆ 6563     ┆ TCAGGTGTG ┆ chr1-5995 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AATGCTGTT ┆ -6563     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TTCTGTTTC ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AAA…      ┆           │
│ 2.700689 ┆ 2.779174   ┆ 2.783492   ┆ 2.708434  ┆ … ┆ 11183    ┆ 12718    ┆ TTGAACTGA ┆ chr1-1118 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AAATCGTTT ┆ 3-12718   │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TGAATAGTC ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTG…      ┆           │
│ …        ┆ …          ┆ …          ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ 0.160837 ┆ 0.12274    ┆ 0.415743   ┆ 0.442518  ┆ … ┆ 56451144 ┆ 56451499 ┆ TCTTTATTT ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GAACATTCG ┆ 1144-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCAAGCGAG ┆ 1499      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCT…      ┆           │
│ 0.502386 ┆ 0.003683   ┆ 0.185817   ┆ 0.184957  ┆ … ┆ 56452461 ┆ 56452791 ┆ ACAGGAGAC ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CACCAGGGT ┆ 2461-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAAGAGGAG ┆ 2791      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCT…      ┆           │
│ 0.973099 ┆ 0.518465   ┆ 0.70947    ┆ 0.691647  ┆ … ┆ 56454009 ┆ 56454588 ┆ CTGATGACC ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TTCTCGGCC ┆ 4009-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AATCACAAT ┆ 4588      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAT…      ┆           │
│ 0.123326 ┆ 0.189685   ┆ 0.418941   ┆ 0.106852  ┆ … ┆ 56455292 ┆ 56455610 ┆ ATTATGTGT ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTATTGGGT ┆ 5292-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCGGGTCAG ┆ 5610      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTG…      ┆           │
│ 0.0036   ┆ 0.527157   ┆ 0.018469   ┆ 0.501148  ┆ … ┆ 56457510 ┆ 56457810 ┆ TAAACCCTA ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ ATGAAGTGT ┆ 7510-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTGTGAATG ┆ 7810      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAC…      ┆           │
└──────────┴────────────┴────────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [8]:
lifelong_cpm_l0_q0 = pl.read_parquet('../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_cpm_l0_q0__seqs.parquet')
lifelong_cpm_l0_q0

shape: (445_300, 79)
┌───────────┬────────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ 14_teeth  ┆ 14_dermal  ┆ 14_periva ┆ 14_perios ┆ … ┆ start    ┆ end      ┆ sequence  ┆ peak_id   │
│ ---       ┆ fibroblast ┆ scular    ┆ teum/tend ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---       │
│ f32       ┆ ---        ┆ ---       ┆ on/ligame ┆   ┆ i64      ┆ i64      ┆ str       ┆ str       │
│           ┆ f32        ┆ f32       ┆ nt        ┆   ┆          ┆          ┆           ┆           │
│           ┆            ┆           ┆ ---       ┆   ┆          ┆          ┆           ┆           │
│           ┆            ┆           ┆ f32       ┆   ┆          ┆          ┆           ┆           │
╞═══════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 0.307579  ┆ 0.399774   ┆ 0.224029  ┆ 0.223661  ┆ … ┆ 1168     ┆ 1395     ┆ TCAAAGAGC ┆ chr1-1168 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ TGTTGCAGC ┆ -1395     │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ ATGAGTGGA ┆           │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ AAA…      ┆           │
│ 0.423126  ┆ 0.486597   ┆ 0.275852  ┆ 0.483911  ┆ … ┆ 3061     ┆ 3345     ┆ TCTGGGTTA ┆ chr1-3061 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ CAAGTTTTA ┆ -3345     │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ GAAGAATTA ┆           │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ ATA…      ┆           │
│ 0.323022  ┆ 0.079409   ┆ 0.452762  ┆ 0.200092  ┆ … ┆ 4198     ┆ 4561     ┆ AATGACTCA ┆ chr1-4198 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ TTAGTATTC ┆ -4561     │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ GTGTTTTTG ┆           │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ GAC…      ┆           │
│ 2.542466  ┆ 2.374374   ┆ 1.207708  ┆ 1.779676  ┆ … ┆ 5995     ┆ 6563     ┆ TCAGGTGTG ┆ chr1-5995 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ AATGCTGTT ┆ -6563     │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ TTCTGTTTC ┆           │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ AAA…      ┆           │
│ 13.791148 ┆ 15.326517  ┆ 14.565765 ┆ 13.696332 ┆ … ┆ 11183    ┆ 12718    ┆ TTGAACTGA ┆ chr1-1118 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ AAATCGTTT ┆ 3-12718   │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ TGAATAGTC ┆           │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ GTG…      ┆           │
│ …         ┆ …          ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ 0.29324   ┆ 0.207025   ┆ 0.626034  ┆ 0.626192  ┆ … ┆ 56451144 ┆ 56451499 ┆ TCTTTATTT ┆ chr9-5645 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ GAACATTCG ┆ 1144-5645 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ TCAAGCGAG ┆ 1499      │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ TCT…      ┆           │
│ 0.736398  ┆ 0.0        ┆ 0.359278  ┆ 0.342519  ┆ … ┆ 56452461 ┆ 56452791 ┆ ACAGGAGAC ┆ chr9-5645 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ CACCAGGGT ┆ 2461-5645 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ CAAGAGGAG ┆ 2791      │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ TCT…      ┆           │
│ 1.682214  ┆ 0.73594    ┆ 1.070504  ┆ 1.002854  ┆ … ┆ 56454009 ┆ 56454588 ┆ CTGATGACC ┆ chr9-5645 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ TTCTCGGCC ┆ 4009-5645 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ AATCACAAT ┆ 4588      │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ CAT…      ┆           │
│ 0.233016  ┆ 0.308113   ┆ 0.63023   ┆ 0.239281  ┆ … ┆ 56455292 ┆ 56455610 ┆ ATTATGTGT ┆ chr9-5645 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ GTATTGGGT ┆ 5292-5645 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ TCGGGTCAG ┆ 5610      │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ GTG…      ┆           │
│ 0.0       ┆ 0.752893   ┆ 0.077924  ┆ 0.705232  ┆ … ┆ 56457510 ┆ 56457810 ┆ TAAACCCTA ┆ chr9-5645 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ ATGAAGTGT ┆ 7510-5645 │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ GTGTGAATG ┆ 7810      │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆ CAC…      ┆           │
└───────────┴────────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [10]:
lifelong_cpm_l1_q0 = pl.read_parquet('../data/lifelong/processed/to_train/train_atac_L2k_g11_lifelong_cpm_l1_q0__seqs.parquet')
lifelong_cpm_l1_q0

shape: (445_300, 79)
┌──────────┬────────────┬────────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ 14_teeth ┆ 14_dermal  ┆ 14_perivas ┆ 14_perios ┆ … ┆ start    ┆ end      ┆ sequence  ┆ peak_id   │
│ ---      ┆ fibroblast ┆ cular      ┆ teum/tend ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---       │
│ f32      ┆ ---        ┆ ---        ┆ on/ligame ┆   ┆ i64      ┆ i64      ┆ str       ┆ str       │
│          ┆ f32        ┆ f32        ┆ nt        ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆            ┆ ---       ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆            ┆ f32       ┆   ┆          ┆          ┆           ┆           │
╞══════════╪════════════╪════════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 0.268178 ┆ 0.336311   ┆ 0.202148   ┆ 0.201847  ┆ … ┆ 1168     ┆ 1395     ┆ TCAAAGAGC ┆ chr1-1168 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TGTTGCAGC ┆ -1395     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ ATGAGTGGA ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AAA…      ┆           │
│ 0.352856 ┆ 0.39649    ┆ 0.243614   ┆ 0.394681  ┆ … ┆ 3061     ┆ 3345     ┆ TCTGGGTTA ┆ chr1-3061 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAAGTTTTA ┆ -3345     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GAAGAATTA ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ ATA…      ┆           │
│ 0.279919 ┆ 0.076414   ┆ 0.373467   ┆ 0.182398  ┆ … ┆ 4198     ┆ 4561     ┆ AATGACTCA ┆ chr1-4198 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TTAGTATTC ┆ -4561     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTGTTTTTG ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GAC…      ┆           │
│ 1.264823 ┆ 1.21621    ┆ 0.791955   ┆ 1.022334  ┆ … ┆ 5995     ┆ 6563     ┆ TCAGGTGTG ┆ chr1-5995 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AATGCTGTT ┆ -6563     │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TTCTGTTTC ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AAA…      ┆           │
│ 2.694029 ┆ 2.792791   ┆ 2.745074   ┆ 2.687598  ┆ … ┆ 11183    ┆ 12718    ┆ TTGAACTGA ┆ chr1-1118 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AAATCGTTT ┆ 3-12718   │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TGAATAGTC ┆           │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTG…      ┆           │
│ …        ┆ …          ┆ …          ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ 0.257151 ┆ 0.188159   ┆ 0.486144   ┆ 0.486241  ┆ … ┆ 56451144 ┆ 56451499 ┆ TCTTTATTT ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GAACATTCG ┆ 1144-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCAAGCGAG ┆ 1499      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCT…      ┆           │
│ 0.551813 ┆ 0.0        ┆ 0.306954   ┆ 0.294547  ┆ … ┆ 56452461 ┆ 56452791 ┆ ACAGGAGAC ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CACCAGGGT ┆ 2461-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAAGAGGAG ┆ 2791      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCT…      ┆           │
│ 0.986643 ┆ 0.551549   ┆ 0.727792   ┆ 0.694573  ┆ … ┆ 56454009 ┆ 56454588 ┆ CTGATGACC ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TTCTCGGCC ┆ 4009-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ AATCACAAT ┆ 4588      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAT…      ┆           │
│ 0.209463 ┆ 0.268585   ┆ 0.488721   ┆ 0.214531  ┆ … ┆ 56455292 ┆ 56455610 ┆ ATTATGTGT ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTATTGGGT ┆ 5292-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ TCGGGTCAG ┆ 5610      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTG…      ┆           │
│ 0.0      ┆ 0.561268   ┆ 0.075037   ┆ 0.533701  ┆ … ┆ 56457510 ┆ 56457810 ┆ TAAACCCTA ┆ chr9-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ ATGAAGTGT ┆ 7510-5645 │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ GTGTGAATG ┆ 7810      │
│          ┆            ┆            ┆           ┆   ┆          ┆          ┆ CAC…      ┆           │
└──────────┴────────────┴────────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [ ]:
# create training data for **EMBRYO**
out_embryo_dir = training.prepare_training_from_df(
    df=embryo_cpm_l1_q1,
    pattern="train_atac_L2k_g11_embryo_cpm_l1_q1__seqs",
    output_dir="../data/embryo/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        # or "random"
    holdout_chroms=None,            # or a list of specified ["1","2"] 
    channel_first=True
)
print("Saved to:", out_embryo_dir)

# create training data for **LIFELONG**
out_lifelong_dir = training.prepare_training_from_df(
    df=lifelong_cpm_l1_q1,
    pattern="train_atac_L2k_g11_lifelong_cpm_l1_q1__seqs",
    output_dir="../data/lifelong/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        
    holdout_chroms=None,       
    channel_first=True
)
print("Saved to:", out_lifelong_dir)

Saved to: ../../data/lifelong/training/train_atac_L2k_g11_lifelong_cpm_l1_q1__seqs/80_20_chrom_split
Saved to: ../../data/merged_embryo2life/training/train_atac_L2k_g11_merged_cpm_l1_q1__seqs/80_20_chrom_split

In [ ]:
## split random - mixed chromosomes 
# create training data for **EMBRYO**
out_embryo_dir = training.prepare_training_from_df(
    df=embryo_cpm_l1_q1,
    pattern="train_atac_L2k_g11_embryo_cpm_l1_q1__seqs",
    output_dir="../data/embryo/training/",
    test_size=0.2,
    random_state=42,
    split_mode="random",        # or "random"
    holdout_chroms=None,            # or a list of specified ["1","2"] 
    channel_first=True
)
print("Saved to:", out_embryo_dir)

# create training data for **LIFELONG**
out_lifelong_dir = training.prepare_training_from_df(
    df=lifelong_cpm_l1_q1,
    pattern="train_atac_L2k_g11_lifelong_cpm_l1_q1__seqs",
    output_dir="../data/lifelong/training/",
    test_size=0.2,
    random_state=42,
    split_mode="random",        
    holdout_chroms=None,       
    channel_first=True
)

Saved to: ../data/embryo/training/train_atac_L2k_g11_embryo_cpm_l1_q1__seqs/80_20_random

In [ ]:
out_embryo_dir_l0 = training.prepare_training_from_df(
    df=embryo_cpm_l0_q0,
    pattern="train_atac_L2k_g11_embryo_cpm_l0_q0__seqs",
    output_dir="../data/embryo/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        # or "random"
    holdout_chroms=None,            # or a list of specified ["1","2"] 
    channel_first=True
)

# create training data for **LIFELONG**
out_lifelong_dir_l0_q0 = training.prepare_training_from_df(
    df=lifelong_cpm_l0_q0,
    pattern="train_atac_L2k_g11_lifelong_cpm_l0_q0__seqs",
    output_dir="../data/lifelong/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        
    holdout_chroms=None,       
    channel_first=True
)

In [ ]:
out_embryo_dir_l1q0 = training.prepare_training_from_df(
    df=embryo_cpm_l1_q0,
    pattern="train_atac_L2k_g11_embryo_cpm_l1_q0__seqs",
    output_dir="../data/embryo/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        # or "random"
    holdout_chroms=None,            # or a list of specified ["1","2"] 
    channel_first=True
)

# create training data for **LIFELONG**
out_lifelong_dir_l0_q0 = training.prepare_training_from_df(
    df=lifelong_cpm_l1_q0,
    pattern="train_atac_L2k_g11_lifelong_cpm_l1_q0__seqs",
    output_dir="../data/lifelong/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        
    holdout_chroms=None,       
    channel_first=True
)

In [ ]:
out_embryo_dir_l1q0 = training.prepare_training_from_df(
    df=embryo_cpm_l0_q1,
    pattern="train_atac_L2k_g11_embryo_raw_l0_q1__seqs",
    output_dir="../data/embryo/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        # or "random"
    holdout_chroms=None,            # or a list of specified ["1","2"] 
    channel_first=True
)

In [ ]:
# create training data for **EMBRYO + LIFELONG**
out_merged_dir = training.prepare_training_from_df(
    df=merged_Cpm_l1_q1,
    pattern="train_atac_L2k_g11_merged_cpm_l1_q1__seqs",
    output_dir="../data/merged_embryo2life/training/",
    test_size=0.2,
    random_state=42,
    split_mode="chromosome",        
    holdout_chroms=None,            
    channel_first=True
)
print("Saved to:", out_merged_dir)

# bundle = load_split_folder(out_dir)
# bundle["X_train"].shape, bundle["Y_train"].shape, bundle["meta"]

AttributeError: module 'zebra_dev.utils.preprocess' has no attribute 'prepare_training_from_df'

### Create train data for RNA

In [2]:
rna_embryo = pd.read_csv('../data/embryo/processed/rna_data_enriched_psd.csv', index_col=0)
print(rna_embryo.shape)
rna_embryo.head()

(26544, 63)

,18_anterior/posterior axis,12_neural keel,5_hypoblast,24_anterior/posterior axis,18_erythroid lineage cell,5_epiblast,18_lateral plate mesoderm,10_anterior/posterior axis,12_anterior/posterior axis,18_primary neuron,...,12_integument,24_immature eye,18_integument,24_periderm/epidermis,18_digestive system,24_central nervous system,24_primary neuron,18_central nervous system,24_erythroid lineage cell,24_segmental plate
rpl13a,5.857117,5.824826,3.413838,6.313237,6.463578,2.643843,4.899677,6.112449,5.610301,5.522120,...,5.727920,6.026385,5.590376,4.972049,4.869890,5.234285,3.818170,5.585933,5.804019,5.487815
khdrbs1a,6.122264,6.536900,6.499459,6.308115,5.110812,6.003681,5.216568,6.766642,6.098865,5.602649,...,3.000000,5.336023,5.045748,3.306467,4.587463,5.118621,3.831246,5.729262,3.331637,5.100458
apoeb,3.069851,4.656436,4.655129,5.135443,2.887316,4.500979,3.287546,5.262438,4.416610,1.978619,...,3.169925,1.805192,6.859398,0.312531,2.877444,1.864325,0.351518,3.186347,0.397705,4.151361
cfl1,4.765997,4.585853,3.999817,5.109143,4.746344,3.242275,4.030919,4.876013,4.445181,4.565309,...,0.000000,4.676847,3.772863,0.661758,3.890680,3.951784,3.086633,4.238597,3.150882,3.872751
polr2d,1.697659,2.096149,1.172371,1.975166,1.579638,0.691351,1.968964,2.115665,1.782080,1.109292,...,2.321928,1.743021,1.325530,0.416848,0.792481,1.262022,0.484377,1.702378,0.665596,1.363183

#### add gene coordinates

In [3]:
gtf_path = "../data/genome/Danio_rerio.GRCz11.111.chr.gtf"
fasta_path = "../data/genome/Danio_rerio.GRCz11.dna.primary_assembly.fa"
gene_info = preprocess.extract_gene_info_from_gtf(gtf_path)
print(gene_info.shape)
gene_info.head()
# merge the gene info with rna_embryo based on gene_name which is the index of rna_embryo
rna_embryo_annot = rna_embryo.merge(gene_info, left_index=True, right_on='gene_name', how='left')
rna_embryo_annot = rna_embryo_annot.set_index('gene_name')
# remove rows with nas in the columns chr, start, end
rna_embryo_annot = rna_embryo_annot.dropna(subset=['chrom', 'start', 'end'])

rna_embryo_annot.head()
# transform start and end to int
rna_embryo_annot['start'] = rna_embryo_annot['start'].astype(int)
rna_embryo_annot['end'] = rna_embryo_annot['end'].astype(int)
rna_embryo_annot['tss_position'] = rna_embryo_annot['tss_position'].astype(int)
rna_embryo_annot.head()
# discard rows with nas in the columns chr, start, end
rna_embryo_annot = rna_embryo_annot.dropna(subset=['chrom', 'start', 'end'])
# drom rows where the chrom is MT
rna_embryo_annot = rna_embryo_annot[rna_embryo_annot['chrom'] != 'MT']
# convert to integer the chrom column
rna_embryo_annot['chrom'] = rna_embryo_annot['chrom'].astype(int)
rna_embryo_annot.head()

(31954, 7)

,18_anterior/posterior axis,12_neural keel,5_hypoblast,24_anterior/posterior axis,18_erythroid lineage cell,5_epiblast,18_lateral plate mesoderm,10_anterior/posterior axis,12_anterior/posterior axis,18_primary neuron,...,24_primary neuron,18_central nervous system,24_erythroid lineage cell,24_segmental plate,chrom,start,end,tss_position,gene_id,strand
gene_name,,,,,,,,,,,,,,,,,,,,,
rpl13a,5.857117,5.824826,3.413838,6.313237,6.463578,2.643843,4.899677,6.112449,5.610301,5.522120,...,3.818170,5.585933,5.804019,5.487815,17,24615091,24618279,24615091,ENSDARG00000044093,+
khdrbs1a,6.122264,6.536900,6.499459,6.308115,5.110812,6.003681,5.216568,6.766642,6.098865,5.602649,...,3.831246,5.729262,3.331637,5.100458,13,45009957,45022527,45022527,ENSDARG00000052856,-
apoeb,3.069851,4.656436,4.655129,5.135443,2.887316,4.500979,3.287546,5.262438,4.416610,1.978619,...,0.351518,3.186347,0.397705,4.151361,16,23960744,23963461,23960744,ENSDARG00000040295,+
cfl1,4.765997,4.585853,3.999817,5.109143,4.746344,3.242275,4.030919,4.876013,4.445181,4.565309,...,3.086633,4.238597,3.150882,3.872751,14,30795559,30801555,30795559,ENSDARG00000021124,+
polr2d,1.697659,2.096149,1.172371,1.975166,1.579638,0.691351,1.968964,2.115665,1.782080,1.109292,...,0.484377,1.702378,0.665596,1.363183,2,1124512,1129721,1124512,ENSDARG00000076509,+

In [5]:
# only the gene sequence
rna_with_seq = preprocess.add_sequences_to_rna(
    rna_embryo_annot,
    fasta_dir="../data/genome",
    save_dir="../data/embryo/processed/to_train"
)

[✓] Saved to ../data/embryo/processed/to_train/rna_with_gene_seq_ba0.csv

In [6]:
# +/- 1000 bp around the tss
rna_with_seq_ba1k = preprocess.add_sequences_to_rna(
    rna_embryo_annot,
    fasta_dir="../data/genome",
    symmetric_bp=1000,
    save_dir="../data/embryo/processed/to_train"
)

[✓] Saved to ../data/embryo/processed/to_train/rna_with_gene_seq_ba1000.csv

In [10]:
# +/- 1000 bp around the tss
rna_with_seq_b1ka500 = preprocess.add_sequences_to_rna(
    rna_embryo_annot,
    fasta_dir="../data/genome",
    before_bp=1000,
    after_bp=500,
    save_dir="../data/embryo/processed/to_train"
)

[✓] Saved to ../data/embryo/processed/to_train/rna_with_gene_seq_ba1000_500.csv

#### expand sequence tensors to include the the accessibility value of each nucleotide across each gene and its flanking regions

## Multiome

In [9]:
import anndata as ad
multiome_data = ad.read_h5ad(
    "../data/multiome/zf_multiome_atlas_full_ATAC_v1_release.h5ad"
)
multiome_data

AnnData object with n_obs × n_vars = 94562 × 640834
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'nCount_ATAC', 'nFeature_ATAC', 'nucleosome_signal', 'nucleosome_percentile', 'TSS.enrichment', 'TSS.percentile', 'nCount_SCT', 'nFeature_SCT', 'global_annotation', 'nCount_peaks_bulk', 'nFeature_peaks_bulk', 'nCount_peaks_celltype', 'nFeature_peaks_celltype', 'nCount_peaks_merged', 'nFeature_peaks_merged', 'SCT.weight', 'peaks_merged.weight', 'nCount_Gene.Activity', 'nFeature_Gene.Activity', 'nCount_peaks_integrated', 'nFeature_peaks_integrated', 'dataset', 'integrated.weight', 'peaks_integrated.weight', 'wsnn_res.0.8', 'seurat_clusters', 'leiden_0.5', 'leiden_0.8', 'leiden_1', 'leiden_1.2', 'leiden_1.5', 'leiden_2', 'leiden_3', 'leiden_4', 'leiden_5', 'leiden_6', 'leiden_7', 'leiden_8', 'leiden_9', 'leiden_10', 'leiden_0.5_merged', 'leiden_0.8_merged', 'leiden_1_merged', 'leiden_1.2_merged', 'leiden_1.5_merged', 'leiden_2_merged', 'leiden_3_merged', 'leiden_4_merged', 'leiden_5_merged', 'leiden_6_merged', 'leiden_7_merged', 'leiden_8_merged', 'leiden_9_merged', 'leiden_10_merged', 'annotation_ML_coarse', 'dev_stage'
    layers: 'counts'

In [ ]:
celltype_col = "annotation_ML_coarse"  #

import scipy.sparse as sp

adata = multiome_data  # your AnnData object

# choose counts matrix
counts = adata.layers["counts"] if "counts" in adata.layers else adata.X

# cell type labels
labels = adata.obs[celltype_col].astype("category")
categories = labels.cat.categories
codes = labels.cat.codes.to_numpy()

# design matrix: cells × celltypes (one-hot)
row = np.arange(adata.n_obs)
col = codes
data = np.ones(adata.n_obs, dtype=np.int8)
design = sp.csr_matrix((data, (row, col)), shape=(adata.n_obs, len(categories)))

# pseudobulk: (celltypes × cells) @ (cells × peaks) → (celltypes × peaks)
pseudobulk = design.T @ counts  # shape: (n_celltypes, n_peaks)

print("pseudobulk shape:", pseudobulk.shape)
# (num_celltypes, num_peaks)

pseudobulk shape: (32, 640834)

In [41]:
# convert to pandas DataFrame (be careful, may be huge!)
pb_df = pd.DataFrame(
    pseudobulk.toarray().T,     # transpose so peaks = rows
    index=adata.var_names,      # peaks
    columns=categories          # celltypes
)

pb_df.iloc[:5, :5]  # preview

             NMPs   PSM  differentiating_neurons  endocrine_pancreas  endoderm
1-32-526       11    28                       14                  12        12
1-2372-3057    17    52                       26                  32        22
1-3427-4032    55   154                       62                  77        34
1-4469-7268   670  1999                      371                 893       491
1-9541-9969   152   493                       80                 179       115

In [ ]:

label_col = "annotation_ML_coarse"  # or "global_annotation"
labels = adata.obs[label_col].astype("category")
counts = adata.layers["counts"] if "counts" in adata.layers else adata.X

# Build a sparse design matrix: cells × celltypes
cats = labels.cat.categories
row = np.arange(adata.n_obs)
col = labels.cat.codes.values
data = np.ones(adata.n_obs, dtype=np.int8)
D = sp.csr_matrix((data, (row, col)), shape=(adata.n_obs, len(cats)))

# Pseudobulk: (celltypes × cells) @ (cells × peaks) = celltypes × peaks
PB = D.T @ counts  # sparse × sparse -> sparse

print("pseudobulk shape:", PB.shape)  # (#celltypes, #peaks)
celltypes = np.array(cats)
peaks = np.array(adata.var_names)

pseudobulk shape: (32, 640834)